plugins {
    id('com.gradleup.shadow')
}

architectury {
    platformSetupLoomIde()
    fabric()
}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation("${libs.fabric.loader.get()}")
    modImplementation("${libs.fabric.api.get()}")

    // Fabric dependencies go here
    //modImplementation("maven.modrinth:lumynlib:${rootProject.property("lumynlib")}-Fabric")
    modImplementation("dev.architectury:architectury-fabric:${libs.versions.arch.api.get()}")
    modImplementation("com.github.glitchfiend:TerraBlender-fabric:${libs.versions.minecraft.get()}-${rootProject.property("terrablender")}")

    modImplementation("com.terraformersmc:modmenu:${rootProject.property("mod_menu")}")

    // Fabric Loader has MixinExtras built-in since 0.15.0 but not MixinSquared
    //include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:${libs.versions.mixinextras.get()}")))
    include(implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:${libs.versions.mixinsquared.get()}")))

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
    filesMatching('fabric.mod.json') {
        expand "mod_id": rootProject.property("mod_id"),
                "mod_name": rootProject.property("mod_name"),
                "mod_version": rootProject.property("mod_version"),
                "mod_description": rootProject.property("mod_description"),
                "mod_authors": rootProject.property("mod_authors"),
                "mod_license": rootProject.property("mod_license"),
                "fabric_loader_version": libs.versions.fabric.loader.get(),
                "fabric_api_version": libs.versions.fabric.api.get(),
                "minecraft_version_constraint": rootProject.property("minecraft_version_constraint_fabric"),
                "architectury_api": libs.versions.arch.api.get(),
                "terrablender": rootProject.property("terrablender")
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
