[versions]
minecraft = "1.20.1"
parchment = "2023.09.03"

# -- insert architectury docs link --
arch_loom = "1.13-SNAPSHOT"
arch_plugin = "3.4-SNAPSHOT"
arch_api = "9.2.14"

# https://files.minecraftforge.net/net/minecraftforge/forge/
# You can bump the version up if you don't plan on keeping compatibility with NeoForge on 1.20.1
forge_loader = "1.20.1-47.1.47"
forge = "47.1.47"

# https://fabricmc.net/develop
fabric_loader = "0.17.1"
fabric_api = "0.92.8+1.20.1"

# https://github.com/GradleUp/shadow/releases
shadow = "8.3.6"

# https://github.com/LlamaLad7/MixinExtras/releases
mixinextras = "0.5.4"
# https://github.com/Bawnorton/MixinSquared/releases
mixinsquared = "0.3.3"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
forge = { module = "net.minecraftforge:forge", version.ref = "forge_loader" }

[plugins]
arch_loom = { id = "dev.architectury.loom", version.ref = "arch_loom" }
arch_plugin = { id = "architectury-plugin", version.ref = "arch_plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }