plugins {
    id("com.gradleup.shadow")
}

def generatedResources = file("src/generated")

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

loom {
    forge {
        mixinConfig "${rootProject.property("mod_id")}.mixins.json",
                "${rootProject.property("mod_id")}-forge.mixins.json"
    }


    runs {
        data {
            data()
            programArgs "--all", "--mod", "${rootProject.property("mod_id")}"
            programArgs "--output", generatedResources.absolutePath
        }
    }
}

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    forge("${libs.forge.get()}")
    modImplementation("${libs.forge.get()}")

    // Forge dependencies go here
    //modImplementation("maven.modrinth:lumynlib:${rootProject.property("lumynlib")}-Forge")
    modImplementation("dev.architectury:architectury:${libs.versions.arch.api.get()}")
    modImplementation("com.github.glitchfiend:TerraBlender-forge:${libs.versions.minecraft.get()}-${rootProject.property("terrablender")}")

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${libs.versions.mixinextras.get()}"))
    implementation(include("io.github.llamalad7:mixinextras-forge:${libs.versions.mixinextras.get()}"))
    compileOnly(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:${libs.versions.mixinsquared.get()}"))
    implementation(include("com.github.bawnorton.mixinsquared:mixinsquared-forge:${libs.versions.mixinsquared.get()}"))

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionForge')
}

processResources {
    filesMatching('META-INF/mods.toml') {
        expand "mod_id": rootProject.property("mod_id"),
                "mod_name": rootProject.property("mod_name"),
                "mod_version": rootProject.property("mod_version"),
                "mod_description": rootProject.property("mod_description"),
                "mod_authors": rootProject.property("mod_authors"),
                "mod_license": rootProject.property("mod_license"),
                "forge_version": libs.versions.forge.asProvider().get(),
                "minecraft_version_constraint": rootProject.property("minecraft_version_constraint_forge"),
                "architectury_api": libs.versions.arch.api.get(),
                "terrablender": rootProject.property("terrablender")
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
